FROM python:3.12-slim

# Create the directory for the application
RUN mkdir -p /opt/status-page
WORKDIR /opt/status-page

# Copy the entire project into the container
COPY . .

# Install system dependencies required for PostgreSQL and other libraries
RUN apt-get update && \
    apt install -y python3 python3-pip python3-venv python3-dev build-essential \
    libxml2-dev libxslt1-dev libffi-dev libpq-dev libssl-dev zlib1g-dev

# Set permissions for the application directory and install Python dependencies
RUN chown -R root:root /opt/status-page && chmod -R 755 /opt/status-page && \
    python3 -m venv venv && \
    . venv/bin/activate && \
    pip install --upgrade pip && pip install -r requirements.txt

# Grant execute permissions to Gunicorn
RUN chmod +x /opt/status-page/venv/bin/gunicorn

# Expose the port that the app will run on
EXPOSE 8001

# Run the application with Gunicorn
CMD ["/opt/status-page/venv/bin/gunicorn", "--pid", "/var/tmp/status-page.pid", \
     "--pythonpath", "/opt/status-page/statuspage", "--config", "/opt/status-page/gunicorn.py", "statuspage.wsgi:application"]
