# Base image
FROM ubuntu:22.04

# Create application directory
RUN mkdir -p /opt/status-page
WORKDIR /opt/status-page

# Copy application code
COPY . .

# Install system dependencies
RUN apt-get update && \
    apt install -y python3 python3-pip python3-venv python3-dev build-essential \
    libxml2-dev libxslt1-dev libffi-dev libpq-dev libssl-dev zlib1g-dev curl && \
    apt-get clean && \
    addgroup --system status-page && \
    adduser --system --ingroup status-page status-page

# Set permissions for the application directory
RUN chown -R status-page:status-page /opt/status-page && chmod -R 755 /opt/status-page

# Create and activate virtual environment without symlinks, install dependencies as root
RUN python3 -m venv --without-pip venv && \
    curl https://bootstrap.pypa.io/get-pip.py | ./venv/bin/python && \
    PATH="/opt/status-page/venv/bin:$PATH" && \
    ./venv/bin/pip install --upgrade pip && \
    ./venv/bin/pip install -r requirements.txt

# Switch back to status-page user for security
USER status-page

# Expose the application port (WSGI PORT)
EXPOSE 8001

# Command to run gunicorn in the virtual environment
CMD ["/opt/status-page/venv/bin/gunicorn", "--pid", "/var/tmp/status-page.pid", "--pythonpath", "/opt/status-page/statuspage", "--config", "/opt/status-page/gunicorn.py", "statuspage.wsgi:application"]
